spring:
  application:
    name: EcommercePlatform
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: ECOMMERCE_DB
    password: Pass123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true
    properties:
      format_sql: true

server:
  servlet:
    context-path: /ecommerce

auth:
  secretKey: djjjjdj866555555%%%%%%%%2222whhhdnndjjdndeajhkfa